require 'rubygems'
require 'crxmake'

pkg_dir = File.dirname(__FILE__)+'/package'
key = ENV['CRX_KEY']

desc 'make chrome extension'
task 'package' do
  Dir.mkdir(pkg_dir) unless File.exists?(pkg_dir)
  Dir.glob("#{pkg_dir}/*").each do |f|
    File.delete(f)
  end

  # create crx
  CrxMake.make(
               :ex_dir => "./src",
               # :pkey => key,
               :crx_output => "#{pkg_dir}/poi.crx",
               :verbose => true,
               :ignorefile => /\.swp/,
               :ignoredir => /\.(?:svn|git|cvs)/
               )
  
  # create zip for Google Extension Gallery
  CrxMake.zip(
              :ex_dir => "./src",
              # :pkey => key,
              :zip_output => "#{pkg_dir}/poi.zip",
              :verbose => true,
              :ignorefile => /\.swp/,
              :ignoredir => /\.(?:svn|git|cvs)/
              )
end

task :default => [:package]
